api_app/urls.py
from django.urls import path

from .views import UserCreateView, LessonListView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

app_name = 'api'

urlpatterns = [
    path('api/register/', UserCreateView.as_view(), name='user-register'),
    path('api/lessons/', LessonListView.as_view(), name='lesson-list'),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

pydev_app/urls.py
from django.urls import path
from .views import HomepageView, DatabaseOfQuestionsView, DetailsTopicView, DetailsLessonView, AdditionalResourceList, \
    AboutUsView, ApiEndpointsView, DetailsCategoryView

urlpatterns = [
    path('', HomepageView.as_view(), name='homepage'),
    path('database/', DatabaseOfQuestionsView.as_view(), name='database'),
    path('resources/', AdditionalResourceList.as_view(), name='resources'),
    path('about_us/', AboutUsView.as_view(), name='about'),
    path('api-endpoints/', ApiEndpointsView.as_view(), name='endpoints'),
    path('category/<slug:slug>/', DetailsCategoryView.as_view(), name='detail_category'),
    path('topic/<slug:slug>/', DetailsTopicView.as_view(), name='detail_topic'),
    path('lesson/<slug:slug>/', DetailsLessonView.as_view(), name='detail_lesson'),
]

pydev_project/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pydev_app.urls')),
    path('', include('users_app.urls')),
    path('', include('api_app.urls')),
    path('accounts/', include('allauth.urls')),
    path('tinymce/', include('tinymce.urls')),
] + debug_toolbar_urls()

users_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import UserRegisterView, UserLoginView, SuccessView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('register/success/', SuccessView.as_view(), name='register_success'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

pydev_app/models.py
from django.db import models
from tinymce.models import HTMLField
from slugify import slugify


class Category(models.Model):

    class Meta:
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    CATEGORY_CHOICES = [
        ('backend', 'Backend'),
        ('frontend', 'Frontend'),
    ]
    name = models.CharField(max_length=50, choices=CATEGORY_CHOICES, unique=True)
    description = models.TextField(blank=False)
    slug = models.SlugField(editable=False, unique=True, max_length=255)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.get_name_display()


class Topic(models.Model):

    name = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=False)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='topics')
    slug = models.SlugField(editable=False, max_length=255)

    class Meta:
        unique_together = ('slug', 'category')

        verbose_name = "Тему"
        verbose_name_plural = "Темы"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Module(models.Model):
    name = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=False)
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE, related_name='modules')
    slug = models.SlugField(editable=False, max_length=255)

    class Meta:
        unique_together = ('slug', 'topic')

        verbose_name = "Модуль"
        verbose_name_plural = "Модули"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    name = models.CharField(max_length=255, blank=False)
    description = HTMLField()
    module = models.ForeignKey('Module', on_delete=models.CASCADE, related_name='lessons')
    slug = models.SlugField(editable=False, max_length=255)

    class Meta:
        unique_together = ('slug', 'module')

        verbose_name = "Урок"
        verbose_name_plural = "Уроки"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Resource(models.Model):

    class Meta:
        verbose_name = "Ресурс"
        verbose_name_plural = "Ресурсы"

    CATEGORY_CHOICES = [
        ('playlist', 'Плейлисты'),
        ('website', 'Сайты'),
        ('book', 'Книги'),
        ('documentation', 'Документация'),
        ('course', 'Курсы'),
    ]

    title = models.CharField(max_length=255)
    url = models.URLField(max_length=2000)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='website')

    def __str__(self):
        return self.title

pydev_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import TemplateView, DetailView, ListView
from .models import Category, Topic, Module, Lesson, Resource


class HomepageView(LoginRequiredMixin, TemplateView):
    template_name = 'pydev_app/homepage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.prefetch_related('topics').all()
        context['categories'] = categories
        return context


class DatabaseOfQuestionsView(LoginRequiredMixin, TemplateView):
    template_name = 'pydev_app/database_of_questions.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = Category.objects.prefetch_related('topics').all()
        context['categories'] = categories
        return context


class DetailsCategoryView(LoginRequiredMixin, DetailView):
    model = Category
    template_name = 'pydev_app/detail_category.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.object
        topics = Topic.objects.filter(category=category)
        context['topics'] = topics
        return context


class DetailsTopicView(LoginRequiredMixin, DetailView):
    model = Topic
    template_name = 'pydev_app/detail_topic.html'
    context_object_name = 'topic'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        topic = self.get_object()
        modules = Module.objects.filter(topic=topic)
        lessons = Lesson.objects.filter(module__in=modules)
        context['modules'] = modules
        context['lessons'] = lessons
        return context


class DetailsLessonView(LoginRequiredMixin, DetailView):
    model = Lesson
    template_name = 'pydev_app/detail_lesson.html'
    context_object_name = 'lesson'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lesson = self.get_object()
        topic = lesson.module.topic
        context['back_url'] = reverse('detail_topic', kwargs={'slug': topic.slug})
        return context


class AdditionalResourceList(LoginRequiredMixin, ListView):
    model = Resource
    template_name = 'pydev_app/additional_resource.html'
    context_object_name = 'resources'

    def get_queryset(self):
        return Resource.objects.all().order_by('category', 'title')


class AboutUsView(LoginRequiredMixin, TemplateView):
    template_name = 'pydev_app/about_us.html'


class ApiEndpointsView(TemplateView):
    template_name = 'pydev_app/api_endpoints.html'

pydev_app/templates/includes/about_site.html
<div class="container-md px-4 py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div>
                <div class="card-body">
                    <h1 class="display-5 fw-bold text-body-emphasis mb-3">Технологии, которые вы видите в действии</h1>
                    <p class="fs-5 mb-4 text-secondary">
                        Практическое применение фреймворков
                    </p>
                    <p class="fs-5 mb-4">
                        Этот сайт является отличным примером использования Django для веб-разработки и PostgreSQL для
                        управления данными. Вы можете видеть, как Python и его фреймворки применяются в реальных
                        проектах, демонстрируя мощь и гибкость современных технологий.
                    </p>
                    <a href="#" class="btn-custom">Посмотреть на GitHub</a>
                </div>
            </div>
        </div>
    </div>
</div>

pydev_app/templates/includes/additional_resources.html
<div class="container-md px-4 py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-5 fw-bold text-body-emphasis mb-3">Дополнительные ресурсы</h1>
            <p class="fs-5 mb-4 text-secondary">
                Рассмотрите варианты дополнительного обучения
            </p>
            <div class="custom-border rounded-3 p-4">
                <div>
                    <p class="fs-5 mb-4">Мы собрали для вас полезные ссылки, которые помогут углубить знания и расширить
                        навыки в программировании.</p>
                    <a href="{% url 'resources' %}" class="btn-custom">Посмотреть все ресурсы</a>
                </div>
            </div>
        </div>
    </div>
</div>

pydev_app/templates/includes/category_cards.html
<div class="container-md px-4 py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-5 fw-bold text-body-emphasis mb-3">Важные темы</h1>
            <p class="fs-5 mb-4 text-secondary">
                Узнайте о ключевых аспектах программирования
            </p>
            <div class="row row-cols-1 row-cols-md-2 g-4">
                {% for category in categories %}
                <div class="col">
                    <div class="custom-card bg-light">
                        <div class="card-body">
                            <h1 class="card-title fw-bold mb-4">{{ category.get_name_display }}</h1>
                            <p class="card-text text-secondary">{{ category.description }}</p>
                            <a href="{% url 'detail_category' category.slug %}" class="btn-custom w-100">Перейти к вопросам</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

pydev_app/templates/includes/footer.html
{% load static %}

<div class="container">
    <footer class="d-flex flex-wrap py-3 custom-border-top align-items-center">
        <a href="{% url 'homepage' %}"
           class="d-inline-flex align-items-center mb-3 mb-lg-0 text-center text-lg-start me-lg-auto link-body-emphasis text-decoration-none">
            <img src="{% static 'svg/Python_logo.svg' %}" alt="Pydev logo" width="38" height="38">
        </a>

        <ul class="nav col-12 col-lg-8 justify-content-end mb-0 d-none d-lg-flex">
            <li class="nav-item"><a href="{% url 'database' %}" class="nav-link px-3 text-body">База вопросов</a></li>
            <li class="nav-item"><a href="{% url 'resources' %}" class="nav-link px-3 text-body">Дополнительно</a></li>
            <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-3 text-body">О нас</a></li>
            <li class="nav-item"><a href="{% url 'endpoints' %}" class="nav-link px-3 text-body">API Endpoints</a></li>
        </ul>
    </footer>
</div>

pydev_app/templates/includes/header.html
{% load static %}

<header class="container-fluid custom-border-bottom fixed-top bg-white">
    <div class="container">
        <div class="py-3">
            <div class="row align-items-center">
                <div class="col-auto d-flex align-items-center">
                    <a href="{% url 'homepage' %}" class="d-flex align-items-center mb-lg-0 text-decoration-none">
                        <img src="{% static 'svg/Pydev_logo.svg' %}" alt="Pydev logo">
                    </a>
                </div>

                <div class="col-auto d-lg-none ms-auto">
                    <button class="btn btn-link" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasMenu" aria-controls="offcanvasMenu">
                        <i class="bi bi-list"></i>
                    </button>
                </div>

                <div class="col d-flex justify-content-center d-none d-lg-flex flex-nowrap">
                    <nav>
                        <ul class="nav mb-0 flex-nowrap">
                            <li class="nav-item">
                                <a href="{% url 'database' %}" class="nav-link px-3 text-body" style="white-space: nowrap;">База вопросов</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'resources' %}" class="nav-link px-3 text-body" style="white-space: nowrap;">Дополнительно</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'about' %}" class="nav-link px-3 text-body" style="white-space: nowrap;">О нас</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'endpoints' %}" class="nav-link px-3 text-body" style="white-space: nowrap;">API</a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <div class="col-auto d-flex align-items-center d-none d-lg-flex">
                    {% if user.is_authenticated %}
                        <span class="me-3">Привет, {{ user.username }}!</span>
                        <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                            {% csrf_token %}
                            <button type="submit" class="btn-custom-outline-secondary">Выйти</button>
                        </form>
                    {% else %}
                        <a href="{% url 'users:register' %}" class="btn-custom-outline-secondary me-3">Регистрация</a>
                        <a href="{% url 'users:login' %}" class="btn-custom">Войти</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasMenu" aria-labelledby="offcanvasMenuLabel">
        <div class="offcanvas-header">
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            {% if user.is_authenticated %}
                <h3 class="d-block mb-2 fw-bold">Привет, {{ user.username }}!</h3>
                <div class="border-bottom mb-3" style="border-bottom: 1px solid #000;"></div>
            {% endif %}
            <a href="{% url 'database' %}" class="nav-link d-block py-2" style="white-space: nowrap;">База вопросов</a>
            <a href="{% url 'resources' %}" class="nav-link d-block py-2" style="white-space: nowrap;">Дополнительно</a>
            <a href="{% url 'about' %}" class="nav-link d-block py-2" style="white-space: nowrap;">О нас</a>
            <a href="{% url 'endpoints' %}" class="nav-link d-block py-2" style="white-space: nowrap;">API</a>
            {% if user.is_authenticated %}
                <form action="{% url 'users:logout' %}" method="post" class="mt-3">
                    {% csrf_token %}
                    <button type="submit" class="btn-custom w-100">Выйти</button>
                </form>
            {% else %}
                <a href="{% url 'users:register' %}" class="btn-custom-outline-secondary w-100 mt-3 mb-2">Регистрация</a>
                <a href="{% url 'users:login' %}" class="btn-custom w-100">Войти</a>
            {% endif %}
        </div>
    </div>
</header>

pydev_app/templates/includes/hero.html
{% load static %}

<div class="container-md px-4 py-4" style="height: 600px; overflow: hidden;">
    <div class="row d-flex justify-content-center align-items-center text-center h-100">
        <div class="col-md-8">
            <img class="d-block mx-auto mb-4" src="{% static 'svg/Python_logo.svg' %}" alt="" width="64" height="64">
            <h1 class="display-5 fw-bold text-body-emphasis">Добро пожаловать в PYDEV</h1>
            <p class="lead mb-4">
                Наша платформа предлагает обширную информацию по программированию на Python, включая Django, DRF,
                Docker, Nginx, SQL и другие технологии. Здесь вы найдете материалы как по бэкенду, так и по фронтенду,
                обеспечивая всестороннее понимание всех ключевых аспектов разработки
            </p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a class="btn-custom" href="{% url 'database' %}">Начать обучение</a>
                <a class="btn-custom-outline-secondary" href="{% url 'about' %}">Узнать больше</a>
            </div>
        </div>
    </div>
</div>

pydev_app/templates/includes/topics_list.html
<div class="container-md px-4 py-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-5 fw-bold text-body-emphasis mb-3">Ключевые технологии</h1>
            <p class="fs-5 mb-4 text-secondary">
                Изучите каждую технологию более подробно
            </p>
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                {% for category in categories %}
                    {% for topic in category.topics.all|slice:":3" %}
                        <div class="col">
                            <a href="{% url 'detail_topic' topic.slug %}" class="btn-custom-outline-secondary d-block p-3">
                                {{ topic.name }}
                            </a>
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>